# Generated by Django 3.2.7 on 2021-10-04 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cattle', models.CharField(choices=[('GADO_LEITEIRO', 'GADO_LEITEIRO'), ('GADO_CORTE', 'GADO_CORTE')], max_length=255)),
                ('id_cattle', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=255)),
                ('birth_day', models.DateField()),
                ('weigth', models.DecimalField(decimal_places=4, max_digits=6, max_length=255)),
                ('qtd_milk', models.DecimalField(decimal_places=4, max_digits=6, max_length=255)),
                ('days_to_lactation', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
