# Generated by Django 3.2.7 on 2021-10-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0002_cattle_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='qtd_milk',
            field=models.DecimalField(decimal_places=4, max_digits=4, max_length=255),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='weigth',
            field=models.DecimalField(decimal_places=4, max_digits=4, max_length=255),
        ),
    ]
