# Generated by Django 3.2.7 on 2022-08-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0003_auto_20211006_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='qtd_milk',
            field=models.DecimalField(decimal_places=2, max_digits=8, max_length=255),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='weigth',
            field=models.DecimalField(decimal_places=2, max_digits=8, max_length=255),
        ),
    ]
