# Generated by Django 3.2.7 on 2022-08-26 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0003_auto_20211006_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.FloatField()),
                ('name', models.CharField(max_length=200)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farm')),
            ],
        ),
    ]
