# Generated by Django 3.2.7 on 2022-08-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasture_farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasture',
            name='farm',
            field=models.IntegerField(default=1),
        ),
    ]
