# Generated by Django 3.2.7 on 2021-10-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_auto_20211006_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='cattles',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='incomes_farm',
        ),
    ]
