# Generated by Django 3.2.7 on 2021-10-06 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('income_farm', '0001_initial'),
        ('cattle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_farm', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('tam', models.CharField(max_length=30)),
                ('cattles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle.cattle')),
                ('incomes_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income_farm.income')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
