# Generated by Django 3.2.7 on 2021-10-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0003_auto_20211006_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='days_to_lactation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='qtd_milk',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='weigth',
            field=models.CharField(max_length=255),
        ),
    ]
