# Generated by Django 3.2.7 on 2021-10-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_farm', '0002_income_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
